### ISSUE TITLE
V2.0.1 vegetation results in panic.

### ISSUE THREAD

**Issue by stefankinell** [rphlo/karttapullautin#114]
I just did a test run with the latest release "v2.0.1 Performance Improvement". I got the following error:

```
Thread 1: Vegetation generation
Generating vegetation...
thread '<unnamed>' panicked at src/main.rs:7217:63:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:509:27:
called `Result::unwrap()` on an `Err` value: Any { .. }
```
I'll try to add the test-file here as reference. I did run it first with last version before 2.0 and it worked well.

@antbern - I'll test on another machine as well, but something seems to have sneaked into the code that was not working well on all files.

21H022_73750_7475_25.laz

The pullauta.ini file is the file below (but changed ending to .txt since GitHub did not like .ini)
[pullauta.txt](https://github.com/user-attachments/files/15543271/pullauta.txt)

**Comment by stefankinell** [comment]
link to my laz-file: https://drive.google.com/file/d/1ZuEl45kZrojgxmmcWUT069r3KqiCAwol/view?usp=share_link

**Comment by antbern** [comment]
@rphlo good catch, I see I accidentally introduced that in #110. Sorry for that 🤖
