### ISSUE TITLE
"thread '<unnamed>' panicked" in batch mode

### ISSUE THREAD

**Issue by stefankinell** [rphlo/karttapullautin#115]
I get an error with several sets of laz-files. The typical output is the following - which then leads to the program stoping:

```
Thread 3: All done!
Thread 3: 23F043_71250_6050_25.laz -> 23F043_71250_6050_25.laz.png
Done
Thread 1: Rendering png map with depressions
Rendering...
Done
Thread 1: Rendering png map without depressions
Rendering...
Done


Thread 1: All done!
Skipping borders_23F043_713_62_5050.laz.png it exists already in output folder.
Skipping 23F043_71250_6150_25.laz.png it exists already in output folder.
Skipping 23F043_71250_6050_25.laz.png it exists already in output folder.
Thread 1: 23F043_71325_6225_25.laz -> 23F043_71325_6225_25.laz.png
thread '<unnamed>' panicked at src/main.rs:7637:59:
Unable to open reader: LasZipError(IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }))
thread 'main' panicked at src/main.rs:509:27:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

I have tried to run the batch with fewer laz-files, e.g. the ones that looked like being handled at the time (i.e. the ones with empty .png-files in the out folder when the program was stopped.) But that subset worked fine.

What looks strange is the reference to `thread '<unnamed>'`. But perhaps that is normal just that you do not see this in the fronted?

So before I dig further with testing different sets of laz-files to see if certain files are the issue rather than the program - can you make anything from the error message above?

**Comment by stefankinell** [comment]
I've done some tests with lazvalidate and found some that were failing. Now I am trying to download the files again to see if the error was in the download. Next is contacting Lantmäteriet...
