### ISSUE TITLE
makevegnew  thread 'main' panicked at src\vegetation.rs:72:6:

### ISSUE THREAD

**Issue by GyDomonkos** [rphlo/karttapullautin#122]
I ran a batch of files and got an Output. Then I altered the vegetation settings and entered the command as specified in the Readme file and got the following result:

**domonkosgyorffy@Samsung:/mnt/c/Users/gyorf/Documents/Gyorffy_Domonkos/Tájfutás/Kartapullautin$ ./pullauta.exe makevegenew**
 
Generating vegetation...
thread 'main' panicked at src\vegetation.rs:72:6:
Can not read file: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Since I had a successful run before, I don't think there could be a Problem with the files.
I'm running kartapullautin on Windows 11 and using Ubuntu as the WSL for the commandline.
Any Ideas on whats wrong?

**Comment by stefankinell** [comment]
@GyDomonkos - just a thought - if you want to do new vegetation on multiple files in batch mode you can use these settings in the .ini-file:

```
# vegeonly, set to 1 to only process the vegetation and skip the contour processing
vegeonly=1
```

By setting vegeonly=1 you will skipp most of the other parts of the generation like contours, and get only vegetation. Which saves a lot of time.
